development:
  username: root
  password: '12345'
  database: merlin_db2
  host: 127.0.0.1
  dialect: mysql
test:
  username: root
  password: null
  database: merlin_db2
  host: 127.0.0.1
  dialect: mysql
production:
  username: root
  password: null
  database: merlin_db2
  host: 127.0.0.1
  dialect: mysql